dag:
  is_thread_op: false
  tracer:
    interval_s: 30
http_port: 2009
op:
  ppyolo_mbv3:
    concurrency: 1

    local_service_conf:
      client_type: local_predictor
      device_type: 2
      devices: '0'
      fetch_list:
      - transpose_1.tmp_0
      - transpose_2.tmp_0
      - transpose_3.tmp_0
      - transpose_4.tmp_0
      - transpose_5.tmp_0
      - transpose_6.tmp_0
      - transpose_7.tmp_0
      - transpose_0.tmp_0
      model_config: serving_server/
rpc_port: 9999
worker_num: 20