MODEL: #MODEL field
  framework: "FastRCNN" 
  backbone:
    name: "ResNetSlowFast"
    depth: 50 
    alpha: 2
    beta: 8
    width_per_group: 64
    fusion_kernel_sz: 5
    fuse_bn_relu: 0
    spatial_strides: [[1, 1], [2, 2], [2, 2], [1, 1]]
    use_pool_af_s2: 0
  head:
    name: "AVARoIHead"  
    bbox_roi_extractor:
      name: "SingleRoIExtractor3D"
      roi_layer_type: "RoIAlign"
      output_size: 8
      with_temporal_pool: True
    bbox_head:
        name: 'BBoxHeadAVA'
        in_channels : 2304
        num_classes : 7 # +backgroud
        multilabel: True
        dropout_ratio: 0.5
    assigner:
      name: 'MaxIoUAssignerAVA'
      pos_iou_thr: 0.9
      neg_iou_thr: 0.9
      min_pos_iou: 0.9
    sampler:
      name: 'RandomSampler'
      num: 32
      pos_fraction: 1
      neg_pos_ub: -1
      add_gt_as_proposals: True
    pos_weight: 1.0
    action_thr: 0.01

DATASET: #DATASET field
  batch_size: 10  #single card bacth size
  valid_batch_size: 1 # 不是1会报错
  test_batch_size: 1 #Optional, test batch size per gpu.
  num_workers: 0
  train:
    format: "AVADataset" #the Class name of the dataset used by youerself
    data_prefix: 'abnormal_action_frames_30fps' #Mandatory, train data root path
    file_path: "abnormal_action_train.csv" #Mandatory, train data index file path
    exclude_file: "excluded_timestamps.csv"
    proposal_file: "frames_proposal_faster_rcnn.pkl"
    label_file: "abnormal_action_list.pbtxt"
    person_det_score_thr: 0.9 #用于识别人的动作时，检测置信度小于该阈值的不考虑
    num_max_proposals: 1000
    timestamp_start: 1 #代码中设置
    timestamp_end: -1 #代码中设置
    num_classes: 7 # with background
    FPS: 15 
  valid: #此处同训练
    format: "AVADataset"
    data_prefix: 'abnormal_action_frames_30fps' #Mandatory, train data root path
    file_path: "abnormal_action_train.csv" #Mandatory, train data index file path
    exclude_file: "excluded_timestamps.csv"
    proposal_file: "frames_proposal_faster_rcnn.pkl"
    label_file: "abnormal_action_list.pbtxt"
    person_det_score_thr: 0.9
    num_max_proposals: 1000
    timestamp_start: -1
    timestamp_end: -1
    test_mode: True
    num_classes: 7 # with background
    FPS: 15
  test:
      format: "AVADataset" #Mandotary, indicate the type of test dataset, please refer to the 'paddlevideo/loader/dataset'.
      data_prefix: 'abnormal_action_frames_30fps' #Mandatory, train data root path
      file_path: "abnormal_action_train.csv" #Mandatory, train data index file path
      exclude_file: "excluded_timestamps.csv"
      proposal_file: "frames_proposal_faster_rcnn.pkl"
      label_file: "abnormal_action_list.pbtxt"
      suffix: "{:05}.jpg"
      person_det_score_thr: 0.9
      num_max_proposals: 1000
      timestamp_start: 900
      timestamp_end: 1800
      test_mode: True
      FPS: 15

PIPELINE:
  train:
    sampler:
      name: "SampleAVAFrames"
      clip_len: 32
      frame_interval: 2
    decoder:
      name: "RawFrameDecode"
    transform: #Mandotary, image transfrom operator
      - RandomRescale:
          scale_range: (256,320)
      - RandomCrop_v2:
          size: 256
      - Flip:
          flip_ratio: 0.5
      - Normalize:
          mean: [123.675, 116.28, 103.53]
          std: [58.395, 57.12, 57.375]
          to_bgr: False
      - PackOutput:
          alpha: 2
  valid:
    sampler:
      name: "SampleAVAFrames"
      clip_len: 32
      frame_interval: 2
    decoder:
      name: "RawFrameDecode"
    transform: #Mandotary, image transfrom operator
      - Rescale: 
          scale_range: (-1, 256)
      - Normalize:
          mean: [123.675, 116.28, 103.53]
          std: [58.395, 57.12, 57.375]
          to_bgr: False
      - PackOutput:
          alpha: 2
  test: #Mandatory, indicate the pipeline to deal with the validing data. please refer to the 'paddlevideo/loader/pipelines/'
    sample:
      name: "SampleAVAFrames" #Sampler type.
      clip_len: 32
      frame_interval: 2
      #test_mode: True
    decoder:
      name: "RawFrameDecode"
      #test_mode: True
    transform: #Mandatory, image transform operator.
      - Rescale: 
          scale_range: (-1, 256)
      - Normalize:
          mean: [123.675, 116.28, 103.53]
          std: [58.395, 57.12, 57.375]
          to_bgr: False
      - PackOutput:
          alpha: 2

OPTIMIZER: #OPTIMIZER field
    name: 'Momentum' #Mandatory, the type of optimizer, associate to the 'paddlevideo/solver/'
    momentum: 0.9
    learning_rate: #Mandatory, the type of learning rate scheduler, associate to the 'paddlevideo/solver/'
        iter_step: True
        name: 'CustomWarmupPiecewiseDecay'
        warmup_epochs: 5 
        warmup_start_lr: 0.0004
        step_base_lr: 0.002 
        lrs: [1, 0.1, 0.01, 0.001, 0.0001, 0.00001]
        gamma: 0.1
        steps: [0, 10, 15]
        max_epoch: 20 
    weight_decay:
        name: 'L2'
        value: 1e-5

METRIC:
    name: 'AVAMetric'
    file_path: "abnormal_action_train.csv" #Mandotary, test data index file path.
    exclude_file: "excluded_timestamps.csv"
    label_file: "abnormal_action_list.pbtxt"
    custom_classes: 8 # +background

INFERENCE:
    name: 'AVA_SlowFast_FastRCNN_Inference_helper'
    config_file_path: 'abnoraml_action.yaml'
    detection_model_name: 'faster_rcnn/faster_rcnn_r50_fpn_1x_coco' 
    detection_model_weights: 'faster_rcnn_r50_fpn_1x_coco.pdparams'
    predict_stepsize: 4
    num_frames: 32
    alpha: 4
    target_size: 256

model_name: AVA_SlowFast_FastRcnn 
save_interval: 10
val_interval: 1 
epochs: 2  #Mandatory, total epoch
log_level: "INFO"

