_BASE_: [
  './coco_detection_main.yml',
  './runtime.yml',
  './picodet_esnet.yml',
  './optimizer_300e.yml',
  './picodet_640_reader.yml',
]

pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/LCNet_x1_5_pretrained.pdparams
weights: output/picodet_lcnet_1_5x_416_coco/best_model
find_unused_parameters: True
use_ema: true
cycle_epoch: 40
snapshot_epoch: 10
epoch: 10

PicoDet:
  backbone: LCNet
  neck: CSPPAN
  head: PicoHead

LCNet:
  scale: 1.5
  feature_maps: [3, 4, 5]

TrainReader:
  batch_size: 20
  
LearningRate:
  base_lr: 0.1
  schedulers:
  - !CosineDecay
    max_epochs: 300
  - !LinearWarmup
    start_factor: 0.1
    steps: 300