worker_num: 2
TrainReader:
  inputs_def:
    num_max_boxes: 20
  sample_transforms:
    - Decode: {}
    - Mixup: {alpha: 1.5, beta: 1.5}
    - RandomDistort: {}
    - RandomExpand: {fill_value: [123.675, 116.28, 103.53]}
    #- RandomCrop: {}
    - RandomFlip: {}
    - Resize: {target_size: [448, 448], keep_ratio: False, interp: 2}
  batch_transforms:
    #- BatchRandomResize: {target_size: [ 416, 448, 480, 512, 544, 576, 608,736,864,992,1080], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeBox: {}
    - PadBox: {num_max_boxes: 50}
    - BboxXYXY2XYWH: {}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
    - Gt2YoloTarget: {anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]], anchors: [[7, 10], [12, 22], [24, 17], [22, 45], [46, 33], [43, 88], [85, 66], [115, 146],[275,240]], downsample_ratios: [32, 16, 8]}
  batch_size: 8
  shuffle: true
  drop_last: true
  mixup_epoch: 25000
  use_shared_memory: true
  #collate_batch: false

EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [448, 448], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 8
  #collate_batch: false

TestReader:
  inputs_def:
    image_shape: [3, 448, 448]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [448, 448], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 1
  #collate_batch: false

