_BASE_: [
  '../fairmot/fairmot_hrnetv2_w18_dlafpn_30e_1088x608.yml',
  '../../datasets/mcmot_vehicle.yml'
]

architecture: FairMOT
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/HRNet_W18_C_pretrained.pdparams
for_mot: True

FairMOT:
  detector: CenterNet
  reid: FairMOTEmbeddingHead
  loss: FairMOTLoss
  tracker: JDETracker # multi-class tracker

CenterNetHead:
  regress_ltrb: False

CenterNetPostProcess:
  regress_ltrb: False
  max_per_img: 200

JDETracker:
  use_byte: True
  match_thres: 0.8
  conf_thres: 0.4
  low_conf_thres: 0.1
  min_box_area: 0
  vertical_ratio: 0

weights: output/mcfairmot_hrnetv2_w18_dlafpn_30e_1088x608_visdrone/model_final

epoch: 30
LearningRate:
  base_lr: 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [15, 22]
    use_warmup: True
  - !BurninWarmup
    steps: 1000

OptimizerBuilder:
  optimizer:
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2

TrainReader:
  batch_size: 8
