_BASE_: [
  '../fairmot/fairmot_dla34_30e_1088x608.yml',
  '../../datasets/mcmot_vehicle.yml'
]

pretrain_weights: https://bj.bcebos.com/v1/paddledet/models/centernet_dla34_140e_coco.pdparams 

FairMOT:
  detector: CenterNet
  reid: FairMOTEmbeddingHead
  loss: FairMOTLoss
  tracker: JDETracker # multi-class tracker

CenterNetHead:
  regress_ltrb: False

CenterNetPostProcess:
  for_mot: True
  regress_ltrb: False
  max_per_img: 200

JDETracker:
  use_byte: True
  match_thres: 0.8
  conf_thres: 0.4
  low_conf_thres: 0.1
  min_box_area: 0
  vertical_ratio: 0

weights: output/mcfairmot_dla34_30e_1088x608_visdrone/model_final

epoch: 30
LearningRate:
  base_lr: 0.0005
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [10, 20]
    use_warmup: False

OptimizerBuilder:
  optimizer:
    type: Adam
  regularizer: NULL
